Prac 5 review request
CharlotteCorbett/CP1404_2021 pull request #1
Opened 2021-04-25 14:04 UTC by CharlotteCorbett

Please check for variable names, incorrect formatting, and anything else that can be done better.
@j-finger

2021-04-26 01:16 UTC, j-finger requested changes
I suggest watching the lecture recordings very closely and playing along in the python terminal and with a test file. Just try to do one week at a time (chronological order is almost essential) and you'll get the hang of it.

2021-04-26 01:16 UTC, j-finger commented on Prac 5/state_names.py
> +               "ACT": "Australian Capital Territory", "VIC": "Victoria", "TAS": "Tasmania"}
Does states_dict change? Could it be name slightly DIFFERENTLY?

2021-04-26 01:16 UTC, j-finger commented on Prac 5/hex_colours.py
> +        user_choice = input("Colour:")
Does this line need to be duplicated (line 10 & 13)? Could it be placed somewhere once else for the same effect? (think indentation)

2021-04-26 01:16 UTC, j-finger commented on Prac 5/hex_colours.py
> +user_choice = input("Colour:")
user_choice is a little ambiguous,  what is the user choosing?

2021-04-26 01:16 UTC, j-finger commented on Prac 5/state_names.py
> +    print("{} is {}".format(state, state_name))
Is this what the question is asking for? Does the user have any input?

2021-04-26 01:16 UTC, j-finger commented on Prac 5/word_occurences.py
> +#         strings_dict[string] = 1
This is functional code, you should use it :)

2021-04-26 01:16 UTC, j-finger commented on Prac 5/word_occurences.py
> +#     print("{} : {}".format(string, string_frequency))
Is _string_ valid outside of the for loop on line 4? Perhaps a **_list_** is **_key_** to printing all the words in the dictionary?

2021-04-29 14:24 UTC, merged

2021-05-24 22:25 UTC, lindsaymarkward commented
@j-finger - this is one of the best code reviews I've seen in CP1404. Thanks for doing a good job 👍